### ISSUE TITLE
Controlling states

### ISSUE THREAD

**Issue by Haraldson** [sogoagain/scrambling-text-js#8]
Hi there @sogoagain!

The text scrambling you’ve implemented looks great.

I’m trying to figure out whether it’s possible to control the states manually, instead of having to use a set timing. My use case is to display people cards in a game, and scramble random text properties, leaving people to respond based on their knowledge and insight offered by the other available (unscrambled) information – I would optimally then unscramble only after they answered, and not based on timing.

I’m in no position to make any demands of course – any hints in the right direction would be appreciated!

**Comment by sogoagain** [comment]
Hello @Haraldson,

First of all, thank you for your interest in `scrambling-text-js`.

I am not sure if I understood your question correctly, but if you are asking whether manually managing the state works like the image below, my answer is as follows:

![scrambling-text-js-with-manual-control](https://user-images.githubusercontent.com/23417465/205908124-05a72ceb-1604-4cde-898c-9ffc6970b15a.gif)

If that is what you are asking, it is difficult to implement with pure 'scrambling-text-js' and would require customization. I have written an example in the link below, so please feel free to refer to it:

- [codesandbox - scrambling-text-js-with-manual-control](https://codesandbox.io/s/scrambling-text-js-with-manual-control-fyxsh2)

A brief description of the modifications is as follows:

'scrambling-text-js' converts a string in three steps:

1. `_encode()` - converts a string to unrecognizable words
2. `_fill()` - matches unrecognized words equal to the length of the original string
3. `_decode()` - converts the scrambled text back to the original word

In the original implementation, calling the `scramble()` method executes all three steps mentioned above. However, in the customized example of the code I provided, only steps 1 and 2 are executed. Step 3 has been changed to be executed using the separately defined `unscramble()` method.

Please note that this feature will not be added separately because it does not match the original intention of `scrambling-text-js`.

I hope this helps. Thank you.
